; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:drive_sys]
platform = ststm32
board = nucleo_l433rc_p
framework = arduino
build_type = debug
build_flags = 
	-D DRIVE
	-D STM32
lib_deps = 
	robtillaart/RunningAverage@^0.4.3
	br3ttb/PID@^1.2.1
	arduino-libraries/Servo@^1.1.8
	paulstoffregen/PWMServo@^2.1

[env:science_sys]
platform = ststm32
board = nucleo_l433rc_p
framework = arduino
build_flags = 
	-D SCIENCE
	-D STM32
lib_deps = 
	robtillaart/RunningAverage@^0.4.3
	br3ttb/PID@^1.2.1
	arduino-libraries/Servo@^1.1.8
	paulstoffregen/PWMServo@^2.1

[env:power_sys]
platform = ststm32
board = nucleo_l433rc_p
framework = arduino
build_flags = 
	-D POWER
	-D STM32
lib_deps = 
	robtillaart/RunningAverage@^0.4.3
	br3ttb/PID@^1.2.1
	arduino-libraries/Servo@^1.1.8
	paulstoffregen/PWMServo@^2.1

[env:upper_arm_sys]
platform = ststm32
board = nucleo_l433rc_p
framework = arduino
build_flags = 
	-D UPPER_ARM
	-D STM32
lib_deps = 
	robtillaart/RunningAverage@^0.4.3
	br3ttb/PID@^1.2.1
	arduino-libraries/Servo@^1.1.8
	paulstoffregen/PWMServo@^2.1

[env:lower_arm_sys]
platform = ststm32
board = nucleo_l433rc_p
framework = arduino
build_flags = 
	-D LOWER_ARM
	-D STM32
lib_deps = 
	robtillaart/RunningAverage@^0.4.3
	br3ttb/PID@^1.2.1
	arduino-libraries/Servo@^1.1.8
	paulstoffregen/PWMServo@^2.1

[env:sensor_sys]
platform = ststm32
board = nucleo_l433rc_p
framework = arduino
build_flags = 
	-D SENSOR
	-D STM32
lib_deps = 
	robtillaart/RunningAverage@^0.4.3
	br3ttb/PID@^1.2.1
	arduino-libraries/Servo@^1.1.8
	paulstoffregen/PWMServo@^2.1
